const js = require("@eslint/js");
const prettier = require("eslint-config-prettier/flat");
const globals = require("globals");
const typescript = require("typescript-eslint");

module.exports = [
  // Generated by `ray`, build output, and this CJS config itself are not source.
  { ignores: ["raycast-env.d.ts", "dist/", "eslint.config.js"] },
  js.configs.recommended,
  ...typescript.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      sourceType: "module",
    },
  },
  prettier,
];
